/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicPublicImport } from './routes/(public)/_public'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as authAuthIndexImport } from './routes/(auth)/_auth.index'
import { Route as publicPublicRegisterImport } from './routes/(public)/_public.register'
import { Route as publicPublicLoginImport } from './routes/(public)/_public.login'
import { Route as authAuthMyTeamPageImport } from './routes/(auth)/_auth.my-team-page'
import { Route as authAuthMatchHistoryImport } from './routes/(auth)/_auth.match-history'
import { Route as authAuthLeaderboardImport } from './routes/(auth)/_auth.leaderboard'
import { Route as authAuthCreateTeamImport } from './routes/(auth)/_auth.create-team'
import { Route as authAuthDraftLeagueIdImport } from './routes/(auth)/_auth.draft.$leagueId'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const publicPublicRoute = publicPublicImport.update({
  id: '/_public',
  getParentRoute: () => publicRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const authAuthIndexRoute = authAuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAuthRoute,
} as any)

const publicPublicRegisterRoute = publicPublicRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => publicPublicRoute,
} as any)

const publicPublicLoginRoute = publicPublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicPublicRoute,
} as any)

const authAuthMyTeamPageRoute = authAuthMyTeamPageImport.update({
  id: '/my-team-page',
  path: '/my-team-page',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthMatchHistoryRoute = authAuthMatchHistoryImport.update({
  id: '/match-history',
  path: '/match-history',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthLeaderboardRoute = authAuthLeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthCreateTeamRoute = authAuthCreateTeamImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthDraftLeagueIdRoute = authAuthDraftLeagueIdImport.update({
  id: '/draft/$leagueId',
  path: '/draft/$leagueId',
  getParentRoute: () => authAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_public': {
      id: '/(public)/_public'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicImport
      parentRoute: typeof publicRoute
    }
    '/(auth)/_auth/create-team': {
      id: '/(auth)/_auth/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof authAuthCreateTeamImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/leaderboard': {
      id: '/(auth)/_auth/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof authAuthLeaderboardImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/match-history': {
      id: '/(auth)/_auth/match-history'
      path: '/match-history'
      fullPath: '/match-history'
      preLoaderRoute: typeof authAuthMatchHistoryImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/my-team-page': {
      id: '/(auth)/_auth/my-team-page'
      path: '/my-team-page'
      fullPath: '/my-team-page'
      preLoaderRoute: typeof authAuthMyTeamPageImport
      parentRoute: typeof authAuthImport
    }
    '/(public)/_public/login': {
      id: '/(public)/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicPublicLoginImport
      parentRoute: typeof publicPublicImport
    }
    '/(public)/_public/register': {
      id: '/(public)/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicPublicRegisterImport
      parentRoute: typeof publicPublicImport
    }
    '/(auth)/_auth/': {
      id: '/(auth)/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthIndexImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/draft/$leagueId': {
      id: '/(auth)/_auth/draft/$leagueId'
      path: '/draft/$leagueId'
      fullPath: '/draft/$leagueId'
      preLoaderRoute: typeof authAuthDraftLeagueIdImport
      parentRoute: typeof authAuthImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthCreateTeamRoute: typeof authAuthCreateTeamRoute
  authAuthLeaderboardRoute: typeof authAuthLeaderboardRoute
  authAuthMatchHistoryRoute: typeof authAuthMatchHistoryRoute
  authAuthMyTeamPageRoute: typeof authAuthMyTeamPageRoute
  authAuthIndexRoute: typeof authAuthIndexRoute
  authAuthDraftLeagueIdRoute: typeof authAuthDraftLeagueIdRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthCreateTeamRoute: authAuthCreateTeamRoute,
  authAuthLeaderboardRoute: authAuthLeaderboardRoute,
  authAuthMatchHistoryRoute: authAuthMatchHistoryRoute,
  authAuthMyTeamPageRoute: authAuthMyTeamPageRoute,
  authAuthIndexRoute: authAuthIndexRoute,
  authAuthDraftLeagueIdRoute: authAuthDraftLeagueIdRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface publicPublicRouteChildren {
  publicPublicLoginRoute: typeof publicPublicLoginRoute
  publicPublicRegisterRoute: typeof publicPublicRegisterRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicLoginRoute: publicPublicLoginRoute,
  publicPublicRegisterRoute: publicPublicRegisterRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

interface publicRouteChildren {
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicPublicRoute: publicPublicRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthIndexRoute
  '/create-team': typeof authAuthCreateTeamRoute
  '/leaderboard': typeof authAuthLeaderboardRoute
  '/match-history': typeof authAuthMatchHistoryRoute
  '/my-team-page': typeof authAuthMyTeamPageRoute
  '/login': typeof publicPublicLoginRoute
  '/register': typeof publicPublicRegisterRoute
  '/draft/$leagueId': typeof authAuthDraftLeagueIdRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthIndexRoute
  '/create-team': typeof authAuthCreateTeamRoute
  '/leaderboard': typeof authAuthLeaderboardRoute
  '/match-history': typeof authAuthMatchHistoryRoute
  '/my-team-page': typeof authAuthMyTeamPageRoute
  '/login': typeof publicPublicLoginRoute
  '/register': typeof publicPublicRegisterRoute
  '/draft/$leagueId': typeof authAuthDraftLeagueIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteWithChildren
  '/(auth)/_auth/create-team': typeof authAuthCreateTeamRoute
  '/(auth)/_auth/leaderboard': typeof authAuthLeaderboardRoute
  '/(auth)/_auth/match-history': typeof authAuthMatchHistoryRoute
  '/(auth)/_auth/my-team-page': typeof authAuthMyTeamPageRoute
  '/(public)/_public/login': typeof publicPublicLoginRoute
  '/(public)/_public/register': typeof publicPublicRegisterRoute
  '/(auth)/_auth/': typeof authAuthIndexRoute
  '/(auth)/_auth/draft/$leagueId': typeof authAuthDraftLeagueIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-team'
    | '/leaderboard'
    | '/match-history'
    | '/my-team-page'
    | '/login'
    | '/register'
    | '/draft/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-team'
    | '/leaderboard'
    | '/match-history'
    | '/my-team-page'
    | '/login'
    | '/register'
    | '/draft/$leagueId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(public)'
    | '/(public)/_public'
    | '/(auth)/_auth/create-team'
    | '/(auth)/_auth/leaderboard'
    | '/(auth)/_auth/match-history'
    | '/(auth)/_auth/my-team-page'
    | '/(public)/_public/login'
    | '/(public)/_public/register'
    | '/(auth)/_auth/'
    | '/(auth)/_auth/draft/$leagueId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(public)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/create-team",
        "/(auth)/_auth/leaderboard",
        "/(auth)/_auth/match-history",
        "/(auth)/_auth/my-team-page",
        "/(auth)/_auth/",
        "/(auth)/_auth/draft/$leagueId"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_public"
      ]
    },
    "/(public)/_public": {
      "filePath": "(public)/_public.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_public/login",
        "/(public)/_public/register"
      ]
    },
    "/(auth)/_auth/create-team": {
      "filePath": "(auth)/_auth.create-team.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/leaderboard": {
      "filePath": "(auth)/_auth.leaderboard.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/match-history": {
      "filePath": "(auth)/_auth.match-history.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/my-team-page": {
      "filePath": "(auth)/_auth.my-team-page.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(public)/_public/login": {
      "filePath": "(public)/_public.login.tsx",
      "parent": "/(public)/_public"
    },
    "/(public)/_public/register": {
      "filePath": "(public)/_public.register.tsx",
      "parent": "/(public)/_public"
    },
    "/(auth)/_auth/": {
      "filePath": "(auth)/_auth.index.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/draft/$leagueId": {
      "filePath": "(auth)/_auth.draft.$leagueId.tsx",
      "parent": "/(auth)/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
